Repository unb-mds/2023-2-JuizVirtual, pull requests merged in 2023-12, with the labels that each got.

#101 [feature request] Criar página de submissões
  apps/submissions/tests.py
  apps/submissions/urls.py
  apps/submissions/views.py
  apps/tasks/tests.py
  apps/tasks/views.py
  server/urls.py
  templates/base.html
  templates/submissions/list.html
Labels: feature request, review needed

#104 [feature request] Add task's constraints field
  .github/workflows/ci.yml
  .github/workflows/test.yml
  apps/tasks/admin.py
  apps/tasks/migrations/0005_task_constraints.py
  apps/tasks/models.py
  apps/tasks/tests.py
  server/settings/base.py
  templates/tasks/detail.html
Labels: feature request, review needed, tests needed

#106 [feature request] Adicionar sistema de pontuação para usuários
  apps/tasks/tests.py
  apps/tasks/views.py
  apps/users/admin.py
  apps/users/migrations/0002_user_score.py
  apps/users/models.py
  apps/users/tests.py
  templates/users/profile.html
Labels: feature request

#111 [feature request]: Users ranking page
  apps/users/tests.py
  apps/users/urls.py
  apps/users/views.py
  templates/base.html
  templates/ranking/list.html
Labels: feature request, review needed

#110 [feature request] Colocar cores na tabela de submissão de acordo como o status
  templates/submissions/list.html
Labels: feature request, review needed

#108 [bug] Add memory and time limits for the tasks
  .pre-commit-config.yaml
  apps/tasks/views.py
  out.txt
  setup.cfg
Labels: feature request

#115 Adicionar e finalizar documentação
  docs/source/reunioes/atas/reuniao-01.rst
  docs/source/reunioes/atas/reuniao-04.rst
  docs/source/reunioes/atas/reuniao-05.rst
  docs/source/reunioes/atas/reuniao-06.rst
  docs/source/reunioes/atas/reuniao-07.rst
  docs/source/reunioes/atas/reuniao-08.rst
  docs/source/reunioes/atas/reuniao-09.rst
  docs/source/reunioes/atas/reuniao-10.rst
  docs/source/reunioes/intro.rst
  docs/source/scrum/intro.rst
  docs/source/scrum/sprints/sprint-0.rst
  docs/source/scrum/sprints/sprint-1.rst
  docs/source/scrum/sprints/sprint-2.rst
  docs/source/scrum/sprints/sprint-3.rst
  docs/source/scrum/sprints/sprint-4.rst
  docs/source/scrum/sprints/sprint-5.rst
  docs/source/scrum/sprints/sprint-6.rst
  docs/source/scrum/sprints/sprint-7.rst
Labels: documentation
