Repository unb-mds/2023-2-JuizVirtual, pull requests merged in 2023-11, with the labels that each got.

#54 [feature request] Adicionar view de registro
  apps/users/forms.py
  apps/users/urls.py
  apps/users/views.py
  server/settings/base.py
  server/urls.py
  templates/base.html
  templates/registration/register.html
Labels: feature request, review needed

#59 [feature request] Add integrations with CI services
  .codeclimate.yml
  .github/workflows/ci.yml
  poetry.lock
  pyproject.toml
Labels: build, ci

#65 [feature request] Initial problems form development
  apps/problems/forms.py
  apps/problems/views.py
Labels: feature request

#57 [feature request] Desenvolvimento dos testes
  apps/contests/tests.py
  apps/problems/tests.py
  apps/users/tests.py
Labels: feature request, review needed, tests needed

#70 [documentation] Adicionar documentação da Sprint 02
  docs/source/scrum/intro.rst
  docs/source/scrum/sprints/sprint-2.rst
Labels: documentation

#74 Remover Nome de Ex-Integrante
  README.md
  docs/source/index.rst
Labels: chore, documentation

#73 [documentation] Adicionar Documentação da Sprint 03
  docs/source/scrum/intro.rst
  docs/source/scrum/sprints/sprint-3.rst
Labels: documentation

#75 [feature request] Estilizar página de login
  poetry.lock
  pyproject.toml
  server/settings/base.py
  templates/registration/login.html
  templates/registration/register.html
Labels: feature request, review needed

#77 [feature request] App inicial de submissões
  apps/submissions/__init__.py
  apps/submissions/migrations/0001_initial.py
  apps/submissions/migrations/0002_alter_submission_code.py
  apps/submissions/migrations/__init__.py
  apps/submissions/models.py
  apps/submissions/tests.py
  core/models.py
  server/settings/base.py
Labels: feature request, review needed, tests needed

#84 [feature request] Render Latex code with Katex
  templates/base.html
Labels: feature request

#81 [bug] Logar automaticamente ao criar uma nova conta
  .pre-commit-config.yaml
  apps/users/tests.py
  apps/users/views.py
Labels: bug, review needed

#87 [feature request] Adicionar arquivos de configuração do Heroku
  Procfile
  app.json
  poetry.lock
  pyproject.toml
  server/settings/development.py
  server/wsgi.py
Labels: chore

#82 [feature request] Adicionar página de perfil do usuário
  apps/users/tests.py
  apps/users/urls.py
  apps/users/views.py
  server/urls.py
  templates/base.html
  templates/users/profile.html
Labels: feature request, review needed

#86 [feature request] Adicionar fomulário inicial de submissão
  apps/submissions/forms.py
  apps/submissions/tests.py
  apps/tasks/forms.py
  apps/tasks/tests.py
  apps/tasks/views.py
  server/urls.py
  static/.keep
  templates/tasks/detail.html
Labels: feature request, review needed

#97 [feature request] Implementar página de outros usuários
  apps/users/urls.py
  apps/users/views.py
  templates/base.html
  templates/users/profile.html
Labels: feature request, review needed

#99 [bug] Não permitir que usuário acessem tasks para contests não iniciados ou cancelados
  apps/tasks/tests.py
  apps/tasks/views.py
Labels: bug

#103 [chore] Adicionar resumo e motivação da aplicação no README
  README.md
Labels: documentation
