Repository unb-mds/2023-2-JuizVirtual, pull requests merged in 2023-10, with the labels that each got.

#18 [feature request] Adicionar página de contest
  apps/contests/__init__.py
  apps/contests/admin.py
  apps/contests/enums.py
  apps/contests/migrations/0001_initial.py
  apps/contests/migrations/0002_contest_cancelled.py
  apps/contests/migrations/__init__.py
  apps/contests/models.py
  apps/contests/urls.py
  apps/contests/views.py
  apps/users/models.py
  server/settings/base.py
  server/urls.py
  templates/base.html
  templates/contests/detail.html
  templates/contests/index.html
Labels: feature request

#22 [documentation] Criar ata da segunda reunião
  docs/source/reunioes/atas/reuniao-02.rst
  docs/source/reunioes/intro.rst
Labels: documentation

#34 [documentation] Adicionar documentação incial das sprints
  docs/source/index.rst
  docs/source/scrum/intro.rst
  docs/source/scrum/sprints/sprint-0.rst
Labels: documentation

#38 [documentation] Adicionar no README e na documentação os passos da instalação
  .tool-versions
  README.md
  docs/_static/initial_screen.png
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
Labels: documentation

#37 [fix] Consertar menu dropdown da barra de navegação
  templates/base.html
  templates/contests/detail.html
  templates/problems/detail.html
Labels: bug

#42 [documentation] Remover código Git Flow no CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: chore

#43 [documentation] Adicionar documentação da ata 03
  docs/source/reunioes/atas/reuniao-03.rst
  docs/source/reunioes/intro.rst
Labels: documentation

#50 [documentation] Adicionar no README informações de instalação
  README.md
Labels: chore, documentation

#52 [documentation] Adicionar documentação da Sprint 1
  docs/source/scrum/intro.rst
  docs/source/scrum/sprints/sprint-1.rst
Labels: documentation

#51 [documentation] Adicionar a Ata da Quarta Reunião
  docs/source/reunioes/atas/reuniao-04.rst
  docs/source/reunioes/intro.rst
Labels: documentation
